FROM reg.dongqiudi.net/business/devops/golang:1.8.3

MAINTAINER latest jingyanlei@dongqiudi.com

RUN cd /go

CMD go run /go/src/thrift-go/server.go

#ENTRYPOINT ["/go/src/cron/microservice/micrun"]

EXPOSE 9090